# Generated by Django 4.0.2 on 2022-03-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_brewed', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('recipe', models.CharField(max_length=500)),
            ],
        ),
    ]
