# Generated by Django 4.1.dev20220215133819 on 2022-03-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recipe',
        ),
    ]
