# Generated by Django 4.0.2 on 2022-03-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipes',
            new_name='recipe',
        ),
    ]
