# Generated by Django 4.1.dev20220215133819 on 2022-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0002_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('bier_sorte', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('ausschlagwuerze', models.CharField(default='', max_length=100)),
                ('sudhausausbeute', models.CharField(max_length=100)),
                ('stamwuerze', models.CharField(max_length=100)),
                ('ibu', models.IntegerField()),
                ('ebc', models.IntegerField()),
                ('alcohol', models.FloatField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('brauwasser', models.CharField(max_length=800)),
                ('schuettung', models.CharField(max_length=800)),
                ('maischplan', models.CharField(max_length=800)),
                ('wuerzekochen', models.CharField(max_length=800)),
                ('gaerung', models.CharField(max_length=800)),
                ('phase', models.CharField(max_length=8000)),
            ],
        ),
    ]
