# Generated by Django 4.0.2 on 2022-03-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0002_rename_recipes_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='messurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField()),
                ('plato', models.FloatField()),
                ('step', models.IntegerField()),
            ],
        ),
    ]
