# Generated by Django 4.0.2 on 2022-03-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0003_messurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messurement',
            name='plato',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='messurement',
            name='temperature',
            field=models.CharField(max_length=10),
        ),
    ]
