# Generated by Django 4.1.dev20220215133819 on 2022-03-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0003_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew_recipe',
            name='number_of_brews',
            field=models.IntegerField(default=0),
        ),
    ]
