# Generated by Django 4.1.dev20220215133819 on 2022-03-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0004_alter_messurement_plato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messurement',
            name='engine',
            field=models.BooleanField(default=False),
        ),
    ]
