# Generated by Django 4.1.dev20220215133819 on 2022-03-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewing', '0005_messurement_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.CharField(max_length=5000),
        ),
    ]
